export const ACADEMIC_DATA = {
  "Professional Degrees (B.Tech / B.E.)": [
    "Computer Science and Engineering",
    "Information Technology",
    "Artificial Intelligence and Machine Learning",
    "Data Science",
    "Cyber Security",
    "Electronics and Communication Engineering",
    "Electrical Engineering",
    "Mechanical Engineering",
    "Civil Engineering",
    "Chemical Engineering",
    "Aerospace Engineering",
    "Aeronautical Engineering",
    "Automobile Engineering",
    "Mechatronics Engineering",
    "Robotics and Automation",
    "Biotechnology",
    "Biomedical Engineering",
    "Petroleum Engineering",
    "Mining Engineering",
    "Agricultural Engineering",
    "Food Technology",
    "Textile Engineering",
    "Marine Engineering",
    "Ocean Engineering and Naval Architecture",
    "Production Engineering",
    "Industrial Engineering",
    "Instrumentation Engineering",
    "Environmental Engineering",
    "Nanotechnology",
    "Metallurgical and Materials Engineering"
  ],
  "Diploma Courses (Polytechnic)": [
    "Diploma in Mechanical Engineering",
    "Diploma in Civil Engineering",
    "Diploma in Electrical Engineering",
    "Diploma in Computer Engineering",
    "Diploma in Electronics and Communication",
    "Diploma in Information Technology",
    "Diploma in Automobile Engineering",
    "Diploma in Chemical Engineering",
    "Diploma in Architecture Assistantship",
    "Diploma in Interior Decoration and Design",
    "Diploma in Fashion Design",
    "Diploma in Medical Laboratory Technology",
    "Diploma in Pharmacy",
    "Diploma in Radiology and Imaging Technology",
    "Diploma in Leather Technology",
    "Diploma in Rubber Technology",
    "Diploma in Printing Technology"
  ],
  "Vocational (ITI)": [
    "Electrician",
    "Fitter",
    "Mechanic Motor Vehicle",
    "Mechanic Diesel",
    "Welder",
    "Machinist",
    "Turner",
    "Draftsman Civil",
    "Draftsman Mechanical",
    "Electronic Mechanic",
    "Instrument Mechanic",
    "Refrigeration and Air Conditioning Technician",
    "Computer Operator and Programming Assistant",
    "Surveyor",
    "Carpenter",
    "Plumber",
    "Foundryman",
    "Sheet Metal Worker",
    "Wireman",
    "Mechanic Agriculture Machinery",
    "Drone Pilot",
    "IoT Technician Smart Agriculture",
    "Solar Technician Electrical"
  ],
  "Postgraduate / Doctoral": [
    "Master of Technology (M.Tech)",
    "Master of Engineering (M.E.)",
    "Master of Computer Applications (MCA)",
    "Post Graduate Diploma in Industrial Automation",
    "Post Graduate Diploma in VLSI Design",
    "Post Graduate Diploma in Cloud Computing",
    "Post Graduate Diploma in Embedded Systems",
    "Doctor of Philosophy (Ph.D.) in Engineering"
  ],
  "Computing & Business (BCA / BBA)": [
    "BCA (General)",
    "BCA Data Analytics",
    "BCA Artificial Intelligence and Machine Learning",
    "BCA Cyber Security",
    "BCA Cloud Computing",
    "BCA Full Stack Development",
    "BCA Web Development",
    "BCA Mobile Application Development",
    "BBA CA (Computer Applications)",
    "BBA Information Technology",
    "BBA Business Analytics",
    "BBA Digital Marketing",
    "BBA Finance",
    "BBA Human Resource Management",
    "BBA International Business",
    "BBA Entrepreneurship",
    "BBA Hospitality and Hotel Management",
    "BBA Sports Management",
    "BBA Aviation Management",
    "BBA Logistics and Supply Chain Management"
  ],
  "Pure & Applied Sciences (B.Sc)": [
    "BSc Physics",
    "BSc Chemistry",
    "BSc Mathematics",
    "BSc Statistics",
    "BSc Computer Science",
    "BSc Information Technology",
    "BSc Biotechnology",
    "BSc Microbiology",
    "BSc Biochemistry",
    "BSc Botany",
    "BSc Zoology",
    "BSc Geology",
    "BSc Forensic Science",
    "BSc Electronics",
    "BSc Nautical Science",
    "BSc Aviation",
    "BSc Animation and Multimedia",
    "BSc Fashion Design",
    "BSc Interior Design",
    "BSc Nutrition and Dietetics",
    "BSc Agriculture",
    "BSc Horticulture",
    "BSc Forestry"
  ],
  "Healthcare & Medical Sciences": [
    "BSc Nursing",
    "BSc Physiotherapy",
    "BSc Medical Laboratory Technology",
    "BSc Radiology and Imaging Technology",
    "BSc Optometry",
    "BSc Operation Theatre Technology",
    "BSc Anesthesia Technology",
    "BSc Cardiac Care Technology",
    "BSc Perfusion Technology",
    "BSc Dialysis Technology",
    "BSc Occupational Therapy",
    "Diploma in Pharmacy",
    "Diploma in General Nursing and Midwifery",
    "Diploma in X Ray Technology",
    "Diploma in Dental Mechanics"
  ],
  "Vocational Degrees (B.Voc)": [
    "BVoc Software Development",
    "BVoc Healthcare Management",
    "BVoc Retail Management",
    "BVoc Green House Technology",
    "BVoc Food Processing and Engineering",
    "BVoc Automotive Mechatronics",
    "BVoc Graphic and Multimedia",
    "BVoc Renewable Energy Management",
    "BVoc Travel and Tourism",
    "BVoc Beauty and Wellness"
  ],
  "Skill-Based Diplomas": [
    "Diploma in Computer Applications",
    "Diploma in Web Design",
    "Diploma in Digital Marketing",
    "Diploma in Hotel Management",
    "Diploma in Travel and Tourism",
    "Diploma in Fashion Design",
    "Diploma in Interior Design",
    "Diploma in Medical Lab Technology",
    "Certificate in Tally and GST",
    "Certificate in Python Programming",
    "Certificate in Data Science",
    "Certificate in Cyber Security",
    "Certificate in Graphic Design"
  ]
};

export const BATCH_YEARS = Array.from(
  { length: (new Date().getFullYear() + 5) - 2018 + 1 }, 
  (_, i) => (2018 + i).toString()
);
